version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Terraform
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Logging in to AWS
      - aws sts get-caller-identity
      - export DEMO_STAGE=$(sed -n '1p' demo-config.txt 2>/dev/null || echo "stage1-basic-ec2")
      - export OPERATION=$(sed -n '2p' demo-config.txt 2>/dev/null || echo "apply")
      - export ENVIRONMENT=$(sed -n '3p' demo-config.txt 2>/dev/null || echo "test")
      - echo "Demo Stage:" $DEMO_STAGE
      - echo "Operation:" $OPERATION
      - echo "Environment:" $ENVIRONMENT
      - cd demo-project/$DEMO_STAGE
      - echo "Ready to" $OPERATION $DEMO_STAGE "in" $ENVIRONMENT "environment"

  build:
    commands:
      - echo Starting Terraform $OPERATION for $DEMO_STAGE
      - terraform init
      - |
        if [ "$OPERATION" = "destroy" ]; then
          echo "Destroying resources..."
          if [ "$DEMO_STAGE" = "stage4-manual-approval" ]; then
            echo "Stage 4: Destroying $ENVIRONMENT environment"
            terraform destroy -var="environment=$ENVIRONMENT" -auto-approve
          else
            terraform destroy -auto-approve
          fi
        else
          echo "Deploying resources..."
          if [ "$DEMO_STAGE" = "stage4-manual-approval" ]; then
            echo "Stage 4: Setting environment to $ENVIRONMENT"
            terraform plan -var="environment=$ENVIRONMENT" -out=tfplan
            terraform apply -auto-approve tfplan
          else
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          fi
        fi

  post_build:
    commands:
      - echo Terraform $OPERATION completed
      - |
        if [ "$OPERATION" = "destroy" ]; then
          echo "✅ $DEMO_STAGE destroyed successfully!"
        else
          terraform output
          echo "✅ $DEMO_STAGE deployment successful!"
        fi

artifacts:
  files:
    - '**/*'