version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Terraform
      - wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Logging in to AWS
      - aws sts get-caller-identity
      - export DEMO_STAGE=$(cat demo-config.txt 2>/dev/null || echo "stage1-basic-ec2")
      - echo "Demo Stage:" $DEMO_STAGE
      - cd demo-project/$DEMO_STAGE
      - echo "Ready to deploy" $DEMO_STAGE

  build:
    commands:
      - echo Starting Terraform deployment for $DEMO_STAGE
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Terraform deployment completed
      - terraform output
      - echo "✅ Deployment successful!"

artifacts:
  files:
    - '**/*'